./main 1 1 1 && python3 completeToOut.py && python3 animations.py
./main 1 1 2 && python3 completeToOut.py && python3 animations.py
./main 1 1 3 && python3 completeToOut.py && python3 animations.py
./main 1 1 4 && python3 completeToOut.py && python3 animations.py
./main 1 1 5 && python3 completeToOut.py && python3 animations.py
./main 1 1 6 && python3 completeToOut.py && python3 animations.py
./main 1 2 1 && python3 completeToOut.py && python3 animations.py
./main 1 2 2 && python3 completeToOut.py && python3 animations.py
./main 1 2 3 && python3 completeToOut.py && python3 animations.py
./main 1 2 4 && python3 completeToOut.py && python3 animations.py
./main 1 2 5 && python3 completeToOut.py && python3 animations.py
./main 1 2 6 && python3 completeToOut.py && python3 animations.py
./main 1 3 1 && python3 completeToOut.py && python3 animations.py
./main 1 3 2 && python3 completeToOut.py && python3 animations.py
./main 1 3 3 && python3 completeToOut.py && python3 animations.py
./main 1 3 4 && python3 completeToOut.py && python3 animations.py
./main 1 3 5 && python3 completeToOut.py && python3 animations.py
./main 1 3 6 && python3 completeToOut.py && python3 animations.py
./main 2 1 1 && python3 completeToOut.py && python3 animations.py
./main 2 1 2 && python3 completeToOut.py && python3 animations.py
./main 2 1 3 && python3 completeToOut.py && python3 animations.py
./main 2 1 4 && python3 completeToOut.py && python3 animations.py
./main 2 1 5 && python3 completeToOut.py && python3 animations.py
./main 2 1 6 && python3 completeToOut.py && python3 animations.py
./main 2 2 1 && python3 completeToOut.py && python3 animations.py
./main 2 2 2 && python3 completeToOut.py && python3 animations.py
./main 2 2 3 && python3 completeToOut.py && python3 animations.py
./main 2 2 4 && python3 completeToOut.py && python3 animations.py
./main 2 2 5 && python3 completeToOut.py && python3 animations.py
./main 2 2 6 && python3 completeToOut.py && python3 animations.py
./main 2 3 1 && python3 completeToOut.py && python3 animations.py
./main 2 3 2 && python3 completeToOut.py && python3 animations.py
./main 2 3 3 && python3 completeToOut.py && python3 animations.py
./main 2 3 4 && python3 completeToOut.py && python3 animations.py
./main 2 3 5 && python3 completeToOut.py && python3 animations.py
./main 2 3 6 && python3 completeToOut.py && python3 animations.py
./main 3 1 1 && python3 completeToOut.py && python3 animations.py
./main 3 1 2 && python3 completeToOut.py && python3 animations.py
./main 3 1 3 && python3 completeToOut.py && python3 animations.py
./main 3 1 4 && python3 completeToOut.py && python3 animations.py
./main 3 1 5 && python3 completeToOut.py && python3 animations.py
./main 3 1 6 && python3 completeToOut.py && python3 animations.py
./main 3 2 1 && python3 completeToOut.py && python3 animations.py
./main 3 2 2 && python3 completeToOut.py && python3 animations.py
./main 3 2 3 && python3 completeToOut.py && python3 animations.py
./main 3 2 4 && python3 completeToOut.py && python3 animations.py
./main 3 2 5 && python3 completeToOut.py && python3 animations.py
./main 3 2 6 && python3 completeToOut.py && python3 animations.py
./main 3 3 1 && python3 completeToOut.py && python3 animations.py
./main 3 3 2 && python3 completeToOut.py && python3 animations.py
./main 3 3 3 && python3 completeToOut.py && python3 animations.py
./main 3 3 4 && python3 completeToOut.py && python3 animations.py
./main 3 3 5 && python3 completeToOut.py && python3 animations.py
./main 3 3 6 && python3 completeToOut.py && python3 animations.py
./main 4 1 1 && python3 completeToOut.py && python3 animations.py
./main 4 1 2 && python3 completeToOut.py && python3 animations.py
./main 4 1 3 && python3 completeToOut.py && python3 animations.py
./main 4 1 4 && python3 completeToOut.py && python3 animations.py
./main 4 1 5 && python3 completeToOut.py && python3 animations.py
./main 4 1 6 && python3 completeToOut.py && python3 animations.py
./main 4 2 1 && python3 completeToOut.py && python3 animations.py
./main 4 2 2 && python3 completeToOut.py && python3 animations.py
./main 4 2 3 && python3 completeToOut.py && python3 animations.py
./main 4 2 4 && python3 completeToOut.py && python3 animations.py
./main 4 2 5 && python3 completeToOut.py && python3 animations.py
./main 4 2 6 && python3 completeToOut.py && python3 animations.py
./main 4 3 1 && python3 completeToOut.py && python3 animations.py
./main 4 3 2 && python3 completeToOut.py && python3 animations.py
./main 4 3 3 && python3 completeToOut.py && python3 animations.py
./main 4 3 4 && python3 completeToOut.py && python3 animations.py
./main 4 3 5 && python3 completeToOut.py && python3 animations.py
./main 4 3 6 && python3 completeToOut.py && python3 animations.py